const namen = [
    'Shrek',
    'Donkey',
    'Princess Fiona',
    'Puss In Boots',
    'Dragon',
    'The Gingerbread Man',
    'King Arthur Pendragon',
    'The Big Bad Wolf',
    'Three Little Pigs',
    'Pinocchio',
    'Three Blind Mice',
    'Dronkeys',
    'Farkle, Fergus, and Felicia',
    'Queen Lillian',
    'King Harold',
    'Doris',
    'Snow White',
    'Cinderella',
    'Sleeping Beauty',
    'Merlin',
    'Brogan',
    'Cookie',
    'Gretched',
    'Humpty Dumpty',
    'Kitty Softpaws',
    'Lord Farquaad',
    'Fairy Godmother',
    'Prince Charming',
    'Rumpelstiltskin',
]

export default namen